# Generated by Django 2.0.13 on 2019-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lion',
            name='major',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lion',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
    ]
