# Generated by Django 2.0.13 on 2019-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0002_auto_20190505_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='lion',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
