# Generated by Django 2.0.13 on 2019-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0005_auto_20190506_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lion',
            name='ddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lion',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
